### PR TITLE
create a list feature to add items

### PR DESCRIPTION
**Pull request by FatemehEngqvist**

### CODE REVIEW

**Review by blagicaz — APPROVED** [review]

**Comment by blagicaz** [comment]
I checked the code, its good to go. If you wanna to check it too, you need to fetch and checkout Fatemeh's branch. That is why i haven't merged it yet.

**Comment by fongv1** [comment]
lgtm

**Review by ZhiChenCZ — COMMENTED** [review]
got it!

**Review by gmoraleslondono — COMMENTED** [review]
👍

**Pull request merged**
